#!/bin/bash
set -e

# This script runs during the first initialization of the Postgres container.
# It creates a Projects table and inserts three rows.

psql "$POSTGRES_DB" <<'SQL'
CREATE TABLE IF NOT EXISTS "Projects" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO "Projects" (id, name) VALUES
    (1, 'foo'),
    (2, 'bar'),
    (3, 'baz')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('"Projects"', 'id'), COALESCE(MAX(id), 1)) FROM "Projects";
SQL
